name: Add issues to org project

on:
  issues:
    types: [opened, reopened, transferred]

jobs:
  add-to-project:
    uses: masakirocorp/.github/.github/workflows/add-to-project.yml@main
    secrets:
      ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
